SET DEFINE OFF;

CREATE TABLE "TB_SLE" (
"SEQ_SLE"	NUMBER(10)		NOT NULL,
"SEQ_PRD"	NUMBER(10)		NOT NULL,
"SLE_NM"	VARCHAR2(256)		NOT NULL,
"DESCES"	VARCHAR2(2048)		NOT NULL,
"IMG"	VARCHAR2(256)		NULL,
"PRICE_SALE"	NUMBER(10)		NOT NULL,
"CD_STATE_SALE"	CHAR(1)		NOT NULL,
"RATE_STAR"	CHAR(1)		NOT NULL,
"DT_SALE_START"	DATE		NOT NULL,
"DT_SALE_END"	DATE		NOT NULL,
"DT_REG"	DATE		NOT NULL,
"REGISTER"	NUMBER(10)		NOT NULL,
"DT_UPT"	DATE		NULL,
"UPDATER"	NUMBER(10)		NULL
);

COMMENT ON COLUMN "TB_SLE"."SEQ_SLE" IS '판매 상품 일련번호';

COMMENT ON COLUMN "TB_SLE"."SEQ_PRD" IS '상품 일련번호';

COMMENT ON COLUMN "TB_SLE"."SLE_NM" IS '판매 상품명';

COMMENT ON COLUMN "TB_SLE"."DESCES" IS '설명';

COMMENT ON COLUMN "TB_SLE"."IMG" IS '이미지(대표)';

COMMENT ON COLUMN "TB_SLE"."PRICE_SALE" IS '판매 가격';

COMMENT ON COLUMN "TB_SLE"."CD_STATE_SALE" IS '판매 상품 상태 코드: 대기(1), 판매(2), 중지(3), 재고 소진(9)';

COMMENT ON COLUMN "TB_SLE"."RATE_STAR" IS '평점';

COMMENT ON COLUMN "TB_SLE"."DT_SALE_START" IS '판매 시작 일시';

COMMENT ON COLUMN "TB_SLE"."DT_SALE_END" IS '판매 종료 일시';

COMMENT ON COLUMN "TB_SLE"."DT_REG" IS '등록 일시';

COMMENT ON COLUMN "TB_SLE"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_SLE"."DT_UPT" IS '수정 일시';

COMMENT ON COLUMN "TB_SLE"."UPDATER" IS '수정자';

CREATE TABLE "TB_PRD" (
"SEQ_PRD"	NUMBER(10)		NOT NULL,
"PRD_NM"	VARCHAR2(128)		NOT NULL,
"CD_CTG_B"	CHAR(1)		NOT NULL,
"CD_CTG_M"	CHAR(1)		NOT NULL,
"PRICE_COST"	NUMBER(10)		NOT NULL,
"COUNT_STOCK"	NUMBER(10)		NOT NULL,
"FLG_DELETE"	CHAR(1)		NOT NULL,
"CD_STATE_PRD"	CHAR(1)		NOT NULL,
"CORP_NM"	VARCHAR2(64)		NOT NULL,
"DT_REG"	DATE		NOT NULL,
"REGISTER"	NUMBER(10)		NOT NULL,
"DT_UPT"	DATE		NULL,
"UPDATER"	NUMBER(10)		NULL
);

COMMENT ON COLUMN "TB_PRD"."SEQ_PRD" IS '상품 일련번호';

COMMENT ON COLUMN "TB_PRD"."PRD_NM" IS '상품명';

COMMENT ON COLUMN "TB_PRD"."CD_CTG_B" IS '상품 카테고리 대분류: 1(기능별), 2(성분별), 3(대상별)';

COMMENT ON COLUMN "TB_PRD"."CD_CTG_M" IS '상품 카테고리 중분류: 1-9';

COMMENT ON COLUMN "TB_PRD"."PRICE_COST" IS '상품 원가';

COMMENT ON COLUMN "TB_PRD"."COUNT_STOCK" IS '상품 재고';

COMMENT ON COLUMN "TB_PRD"."FLG_DELETE" IS '삭제 여부: N(기본값), Y(삭제 처리)';

COMMENT ON COLUMN "TB_PRD"."CD_STATE_PRD" IS '판매 상품 상태 코드: 대기(1), 판매(2), 중지(3), 재고 소진(9)';

COMMENT ON COLUMN "TB_PRD"."DT_REG" IS '등록 일시';

COMMENT ON COLUMN "TB_PRD"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_PRD"."DT_UPT" IS '수정 일시';

COMMENT ON COLUMN "TB_PRD"."UPDATER" IS '수정자';

CREATE TABLE "TB_SLE_IMG" (
"SEQ_SLE_IMG"	NUMBER(10)		NOT NULL,
"SEQ_PRD"	NUMBER(10)		NOT NULL,
"IMG"	VARCHAR2(256)		NOT NULL,
"DT_REG"	DATE		NOT NULL,
"REGISTER"	NUMBER(10)		NOT NULL
);

COMMENT ON COLUMN "TB_SLE_IMG"."SEQ_SLE_IMG" IS '판매 상품 이미지 일련번호';

COMMENT ON COLUMN "TB_SLE_IMG"."SEQ_PRD" IS '상품 일련번호';

COMMENT ON COLUMN "TB_SLE_IMG"."IMG" IS '이미지';

COMMENT ON COLUMN "TB_SLE_IMG"."DT_REG" IS '등록일시';

COMMENT ON COLUMN "TB_SLE_IMG"."REGISTER" IS '등록자';