-- 16개
DELETE FROM TB_BBS;
DELETE FROM TB_BEST;
DELETE FROM TB_BSK;
DELETE FROM TB_BUY_DTL;
DELETE FROM TB_BUY_MST;
DELETE FROM TB_HP_SUR;
DELETE FROM TB_HP_SUR_MBR;
DELETE FROM TB_LIKE;
DELETE FROM TB_MBR_DTL;
DELETE FROM TB_MBR_MST;
DELETE FROM TB_MBR_POINT;
DELETE FROM TB_MNG;
DELETE FROM TB_PAY;
DELETE FROM TB_SLE;
DELETE FROM TB_SLE_IMG;
DELETE FROM TB_TRM_AGR;
COMMIT;

/*
DROP INDEX IDX_TB_MBR_LOGIN;
ALTER TABLE TB_MBR_MST DROP CONSTRAINT UK1_TB_MBR;

DROP TABLE TB_BBS;
DROP TABLE TB_BEST;
DROP TABLE TB_BSK;
DROP TABLE TB_BUY_DTL;
DROP TABLE TB_BUY_MST;
DROP TABLE TB_HP_SUR;
DROP TABLE TB_HP_SUR_MBR;
DROP TABLE TB_LIKE;
DROP TABLE TB_MBR_DTL;
DROP TABLE TB_MBR_MST CASCADE CONSTRAINTS;
DROP TABLE TB_MBR_POINT;
DROP TABLE TB_MNG;
DROP TABLE TB_PAY;
DROP TABLE TB_SLE;
DROP TABLE TB_SLE_IMG;
DROP TABLE TB_TRM_AGR;
COMMIT;

DROP SEQUENCE TB_BBS;
DROP SEQUENCE TB_BEST;
DROP SEQUENCE TB_BSK;
DROP SEQUENCE TB_BUY_DTL;
DROP SEQUENCE TB_BUY_MST;
DROP SEQUENCE TB_HP_SUR;
DROP SEQUENCE TB_HP_SUR_MBR;
DROP SEQUENCE TB_LIKE;
DROP SEQUENCE TB_MBR_DTL;
DROP SEQUENCE TB_MBR_MST;
DROP SEQUENCE TB_MBR_POINT;
DROP SEQUENCE TB_MNG;
DROP SEQUENCE TB_PAY;
DROP SEQUENCE TB_SLE;
DROP SEQUENCE TB_SLE_IMG;
DROP SEQUENCE TB_TRM_AGR;
COMMIT;
*/

-- 휴지통 비우기
-- purge recyclebin;